#!/bin/sh /etc/rc.common

START=90

start(){
	if [ ! -f "/var/run/vlmcsd.pid" ]; then
		/usr/bin/vlmcsd -i /etc/vlmcsd.ini
		echo "KMS Server has started."
	else
		echo "KMS Server has already started."
	fi
}

stop(){
	if [ ! -f "/var/run/vlmcsd.pid" ]; then
		echo "KMS Server is not running."
	else
		pid=`cat /var/run/vlmcsd.pid`
		kill $pid
		rm -f /var/run/vlmcsd.pid
		echo "KMS Server has stopped."
	fi
}

restart(){
	stop
	sleep 1
	start
	echo "KMS Server has restarted."
}
